version: 2.1

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:9.0

    environment:
      MSBUILDDISABLENODEREUSE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      MSBUILDTERMINALLOGGER: false

    steps:
      - checkout

      - run:
          name: Restore dependencies
          command: dotnet restore

      - run:
          name: Build solution
          command: dotnet build --no-restore --configuration Release

      - run:
          name: Run integration tests and collect results
          command: |
            mkdir -p TestResults
            dotnet test --no-build --configuration Release \
              --logger "trx;LogFileName=test-results.trx" \
              --results-directory TestResults \
              --verbosity quiet

      - store_test_results:
          path: TestResults

      - store_artifacts:
          path: TestResults
          destination: test-results

workflows:
  run-.net-api-integration-tests:
    jobs:
      - test