name: .NET Integration Tests

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: '.NET SDK version'
        required: false
        default: '9.0.x'
        type: string
      build-configuration:
        description: 'Build configuration'
        required: false
        default: 'Release'
        type: string
    outputs:
      test-results:
        description: 'Test execution results'
        value: ${{ jobs.dotnet-tests.outputs.test-results }}

permissions:
  checks: write
  contents: read

jobs:
  dotnet-tests:
    name: .NET Integration Tests
    runs-on: ubuntu-latest
    outputs:
      test-results: ${{ steps.test-run.outputs.test-results }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Cache .NET dependencies
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore IntegrationTests/restfulapidev-integration-tests.csproj
        working-directory: ${{ github.workspace }}

      - name: Build solution
        run: dotnet build IntegrationTests/restfulapidev-integration-tests.csproj --no-restore --configuration ${{ inputs.build-configuration }}
        working-directory: ${{ github.workspace }}

      - name: Run tests
        id: test-run
        run: |
          echo "Creating test results directory..."
          mkdir -p ./test-results
          
          echo "Running dotnet test..."
          dotnet test IntegrationTests/restfulapidev-integration-tests.csproj \
            --no-build \
            --configuration ${{ inputs.build-configuration }} \
            --logger "trx;LogFileName=${{ github.workspace }}/test-results/integration-test-results.trx" \
            --logger "console;verbosity=normal" \
            || echo "Tests completed with errors (possibly due to API rate limiting)"
          
          echo "Checking if TRX file was created..."
          if [ -f "${{ github.workspace }}/test-results/integration-test-results.trx" ]; then
            echo "TRX file found!"
            ls -la "${{ github.workspace }}/test-results/"
            echo "test-results=success" >> $GITHUB_OUTPUT
          else
            echo "TRX file not found!"
            ls -la "${{ github.workspace }}/test-results/" || echo "test-results directory not found"
            echo "test-results=failed" >> $GITHUB_OUTPUT
          fi
        working-directory: ${{ github.workspace }}
        continue-on-error: true

      - name: Find test results (debug)
        if: always()
        run: find . -name 'integration-test-results.trx' -print
        working-directory: ${{ github.workspace }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: 'test-results/integration-test-results.trx'
          retention-days: 30

      - name: Publish .NET Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: 'test-results/integration-test-results.trx'
          check_name: '.NET Integration Test Results'